services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:5879"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 5879 --reload
    networks:
      - app_network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge